services:
  app_node:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db_node
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./node/.env:/usr/src/app/.env
    environment:
      DB_HOST: db_node
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      DB_PORT: 5432

  db_node:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5430:5432"
    volumes:
      - postgres_data_match:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_match:
